version: "3.2"
services:
  micrudspringboot:
    image: micrud
    build:
      context: ""
      dockerfile: ./Dockerfile
    ports:
      - "8081:8081"
    links:
      - server
    networks:
      - myNetwork
    environment:
      SPRING.DATASOURCE.URL: jdbc:postgresql://server:5432/test
      SPRING.DATASOURCE.USERNAME: postgres
      SPRING.DATASOURCE.PASSWORD: contrasena
      HIBERNATE.DIALECT: org.hibernate.dialect.PostgreSQLDialect
      SPRING.DATASOURCE.DRIVERCLASSNAME: org.postgresql.Driver
      SPRING.DATASOURCE.INITIALIZATION-MODE: always
      SPRING.DATASOURCE.INITIALIZE: true
      SPRING.DATASOURCE.SCHEMA: classpath:/schema.sql
      SPRING.DATASOURCE.CONTINUE-ON-ERROR: true
      server.port: 8081
    depends_on:
      - server

  server:
    image: postgres
    networks:
      - myNetwork
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: contrasena
      POSTGRES_DB: test

networks:
  myNetwork: